### ISSUE TITLE
Security Monkey 2.0 Tracker

### ISSUE THREAD

**Issue by mikegrima** [Netflix/security_monkey#1102]
We are actively working on a 2.0 release that will have a number of awesome and very important features.

The most important of which is a brand new UI and Python 3 support!

The following list documents some of the most important changes that must be completed:

- [ ] New UI written in ReactJS (IN PROGRESS)
- [ ] Python 3 migration (IN PROGRESS)
- [ ] Strip out `flask_security`; replace with standard JWTs (IN PROGRESS)
- [ ] Remove all existing RBAC logic and replace it with `flask_principal` needs (IN PROGRESS)
- [ ] Go through each and every API, verify that they work properly and have adequate unit tests (IN PROGRESS)
- [ ] Clean up the class registries to make use of a singleton (completed for Account registries) (IN PROGRESS)

This is being developed in the `2.0` branch.

**Comment by mikegrima** [comment]
Just completed:
- New JWT logic is now implemented and in place for the `account.py` view.
- Bug fixes and proper unit tests for `account.py` and a bunch of other code that it calls.

Next to complete: `account_bulk_update.py`.

**Comment by ottogroup-com** [comment]
@mikegrima 
First of all let me say that we are very happy about the objective of a Security Monkey 2.0. We are using Security Monkey a lot lately for our Cloud deployment and are quite happy with the overall architecture and the extensibility. We currently use it in a GCP environment with 50+ projects where we also found some issues which we try to address via PR's which works very well. Nevertheless we found also some pain points which we would like to mention with the hope they get considered for the Security Monkey 2.0 roadmap.
- We currently realize the account management (which are projects in GCP terms) via a cron-job which syncs GCP projects with security-monkey accounts, add them if needed, or deactivate resp. reactivate if the status of the projects changes over time. This feels cumbersome and was something we had to invent in order to use security-monkey in a GCP context.
- Our users can use Google SSO to login to the Security Monkey UI. Currently it is not possible to give a user for example the Justify role for some projects (accounts) and only Viewer role on other projects. An example would be that a product team has several projects for dev/qa/prod and a team consists of developers and team-admins. As a security-monkey administrator I would like to give only team-admins the possibility to justify issues and developers viewer rights. And this only for a subset of accounts which would correspond to their GCP projects. 
- We furthermore implemented a white-listing feature for auditors so that product team-admins can propose that for a certain combination of technology, check and item where no issues will be generated. An example would that GCE instances managed by GKE in general have an external IP address which would generate an issue which then have to be justified. Due to the nature of GKE where nodes can be autoscaled this is very cumbersome. If there is general interest we can contribute the whitelisting feature.
- Security Monkey due to its name is a security tool but due to its architecture it has the potential to be used in a wider range for cloud controlling aspects. We are thinking of maybe using it for cost-controlling aspects in a cloud environment in a sense of a Cloud Resource Controlling tool. We have trouble to align our need with the mission of security-monkey. Maybe you address our concerns by mentioning which tools are better suited for cost monitoring & controlling. What do you use for that problem space?

Keep up the great work and thanks for open-sourcing security-monkey it is being a great journey since [Initial commit](https://github.com/Netflix/security_monkey/commit/e989d87806f04c5540b47a39dcce864f6d0bc9a6)

**Comment by mikegrima** [comment]
Hello @ottogroup-com :  

**A central theme to note is:**

In general, Netflix's use cases around Security Monkey are quite different from the rest of the OSS community, and as such, many features are a low priority/not a priority for us to fix. Generally speaking, we use Security Monkey as a quick and easy way of getting the current and historical configuration of an item in our environment. With regards to issues and auditors, we are building out other tooling to identify and respond to them as they occur.

At the time Security Monkey was developed (2014), Netflix’s AWS environment was much, much smaller. Since then, our infrastructure massively grew in size and complexity. Thus, having one tool to do everything simply didn’t scale. The current theme and priority for us (internally) with Security Monkey is to de-couple items from it as much as possible and to migrate SM's core components onto other tools that can better handle the size of our environment and scale horizontally. A notable example is our effort to have Security Monkey rely on external event-driven Lambda functions (see [Historical](https://netflix-skunkworks.github.io/historical/)) and only operate on known changes that occur, as they occur with context on who/what performed the change. This is a departure from the existing Security Monkey implementation of actively watching our environments (polling model) and migrating to receiving the changes that happen via a push/event model. Solutions like Historical (still in very active development) permanently solve the massive scalability issues that we encountered.

I’m more than happy to chat over LinkedIn should you have any other questions/feedback to provide.

**All that being said, please see my responses inline:**

> We currently realize the account management (which are projects in GCP terms) via a cron-job which syncs GCP projects with security-monkey accounts, add them if needed, or deactivate resp. reactivate if the status of the projects changes over time. This feels cumbersome and was something we had to invent in order to use security-monkey in a GCP context.

Automated account management is generally a pain. Internally, we developed a tool called SWAG(https://github.com/Netflix-Skunkworks/swag-api, and https://github.com/Netflix-Skunkworks/swag-client), which is an account metadata service. We have integrated this into Security Monkey to sync with all of our AWS accounts (it also supports GCP and any other type of cloud account infrastructure you would want to manage). The docs are lacking at the moment, and beefing that up is a priority for us.

The other really big pain point is that due to the distributed nature of the watchers, we currently need to bounce the scheduler whenever there is a change. This *could* be done more programmatically, however, this is not a priority for us to fix. We mostly bounce things regularly since we have ephemeral instances, and this will be a non-issue when we start pulling data from Historical.

> Our users can use Google SSO to login to the Security Monkey UI. Currently it is not possible to give a user for example the Justify role for some projects (accounts) and only Viewer role on other projects. An example would be that a product team has several projects for dev/qa/prod and a team consists of developers and team-admins. As a security-monkey administrator I would like to give only team-admins the possibility to justify issues and developers viewer rights. And this only for a subset of accounts which would correspond to their GCP projects.

This has been requested by a number by other users as well. Netflix presently does not have this use case, and as such, it is not a priority for us to implement. That being said, the changes that are being made in 2.0 will make it massively easier to implement this capability.

> We furthermore implemented a white-listing feature for auditors so that product team-admins can propose that for a certain combination of technology, check and item where no issues will be generated. An example would that GCE instances managed by GKE in general have an external IP address which would generate an issue which then have to be justified. Due to the nature of GKE where nodes can be autoscaled this is very cumbersome. If there is general interest we can contribute the whitelisting feature.

The issue system has been a pain-point for many users. Internally, we are moving to other tooling to detect and resolve issues as they come up (see the central theme above).

> Security Monkey due to its name is a security tool but due to its architecture it has the potential to be used in a wider range for cloud controlling aspects. We are thinking of maybe using it for cost-controlling aspects in a cloud environment in a sense of a Cloud Resource Controlling tool. We have trouble to align our need with the mission of security-monkey. Maybe you address our concerns by mentioning which tools are better suited for cost monitoring & controlling. What do you use for that problem space?

I don’t work on cost monitoring and management, so I can’t really comment too much on that space. However, about a year or so ago, for a fun hack day exercise, I wrote watchers and auditors for GitHub organizations. Security Monkey has been a fantastic tool for tracking our repos, users, and teams across our many GitHub organizations (in fact, I encourage you to use that feature if you have GitHub resources and aren’t using it already). In general, Security Monkey is a great tool for tracking assets and their changes. Thus, if something can be seen as an asset, with changes to track over time, and can be audited, then SM is a potential tool for it.

**Comment by mikegrima** [comment]
Completed the `audit_scores` API. Next up is `auditor_settings`.

**Comment by ottogroup-com** [comment]
@mikegrima
Thank you for your elaborate answer and for clarifying the central theme around Security Monkey. Just to make thinks clear we are far away from pointing out weak spots from Security Monkey but we rather want to discuss the areas of improvement for Security Monkey where we see potential and also are interested in contributing. 

**To your mentioned topics:**
We had also noticed some scalability issues with Security Monkey where find_changes actually has a considerable long run-time when number of accounts, checks and technologies increases. Thus the idea of a event-driven approach seems very appealing and interesting. We will definitely have an eye on how [Historical ](https://netflix-skunkworks.github.io/historical/) evolves. About SWAG it seems useful though I might not catched the full idea [#49](https://github.com/Netflix-Skunkworks/swag-client/issues/49#issuecomment-359103256) helped a bit.

I more than happy to catch up with you on LinkedIn for further discussions.

**Comment by mikegrima** [comment]
We will not be moving forward with SM 2.0 as it will require a massive effort. Internally, we are undergoing another initiative to replace Security Monkey.

**Comment by mrahbar** [comment]
@mikegrima this is unfortunate to here. Can you please share some information what the initiative to replace Security Monkey are?

**Comment by mikegrima** [comment]
We're moving to AWS Config and internal tooling to wrap it.
